// PLACEHOLDER — replace this file with the one generated by `flutterfire configure`.
//
// Steps:
// 1. Install FlutterFire CLI:    dart pub global activate flutterfire_cli
// 2. From project root, run:     flutterfire configure
// 3. Choose your Firebase project, select Android only.
// 4. The CLI writes `lib/firebase_options.dart` (which is .gitignored).
// 5. Delete this template once `firebase_options.dart` exists.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'REPLACE_ME',
      appId: 'REPLACE_ME',
      messagingSenderId: 'REPLACE_ME',
      projectId: 'REPLACE_ME',
      storageBucket: 'REPLACE_ME',
    );
  }
}
